'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
'''


#horrible wrong solution clunky

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if len(s) == 0:
            return t

        s = list(s)
        s.sort()

        t = list(t)
        t.sort()               

        d = dict()

        that_letter = ''
        for i in range(len(t)):
            if t[i] not in d:
                d[ t[i] ] = 1
            else:
                that_letter = t[i]
                break
        if len(that_letter) > 0:        
            return that_letter


        else:
            s = ''.join(s)
            for i in range(len(t)):
                if t[i] not in s:
                    that_letter = t[i]
                    return that_letter

#TIP INSIGHT: what did i learn? i was thinking too much of this, trying to cover every corner case, but the problem is that here YOU NEED TO COUNT every letter - so you use COUNT!!!!!!!!!!         
# good
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in t:
            if t.count(i) != s.count(i):
                return i

#using counter

from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
    	return list(Counter(t) - Counter(s))[0]





